name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    
    # check out sources that will be used for autodocs, plus readme
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install sphinx sphinx_rtd_theme myst_parser
      
      - name: Sphinx generate rst files
        run: |
          sphinx-apidoc --private --module-first -f -o docs src src/module1
          # sphinx-apidoc --no-headings --private --module-first -f -o docs src src/module2
          # sphinx-apidoc --no-toc --module-first -o docs src src/module2
          # sphinx-apidoc -o docs src src\module2
      
      - name: Sphinx generate HTML files
        run: |
          sphinx-build docs _build
          # sphinx-build docs _build -b dirhtml

      - name: Create GitHub Pages branch
        run: |
          git config --global user.name ${{ secrets.GITHUB_ACTOR }}
          git config --global user.email ${{ secrets.GITHUB_ACTOR }}@users.noreply.github.com
          git checkout gh-pages
          git rm -rf .
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true
